// Kaufland brochure products — week 13.04–19.04.2026
// Prices in EUR · Nutritional values per 100 g (0 = not applicable)
export const KAUFLAND_PRODUCTS = [
  // ── MEAT & DELI ───────────────────────────────────────────────────────────
  { name: 'Пилешко бутче с гръб', price: 1.52, unit: 'кг', category: 'meat', protein: 18, calories: 215, isHealthy: true },
  { name: 'Пилешки крила', price: 3.06, unit: 'кг', category: 'meat', protein: 20, calories: 203, isHealthy: true },
  { name: 'Пилешка пържола от бут', price: 4.59, unit: 'кг', category: 'meat', protein: 19, calories: 165, isHealthy: true },
  { name: 'Мляно свинско месо', price: 5.11, unit: 'кг', category: 'meat', protein: 17, calories: 263, isHealthy: false },
  { name: 'Свински врат с кост', price: 4.08, unit: 'кг', category: 'meat', protein: 16, calories: 258, isHealthy: false },
  { name: 'Свинска плешка без кост', price: 2.96, unit: 'кг', category: 'meat', protein: 19, calories: 186, isHealthy: false },
  { name: 'Свински ребра', price: 4.08, unit: 'кг', category: 'meat', protein: 15, calories: 290, isHealthy: false },
  { name: 'Свинско филе варено-пушено', price: 5.00, unit: 'кг', category: 'meat', protein: 22, calories: 145, isHealthy: true },
  { name: 'Мариновани свински гърди с кост', price: 5.62, unit: 'кг', category: 'meat', protein: 15, calories: 310, isHealthy: false },
  { name: 'МИТИ Свинска флейка', price: 5.00, unit: 'кг', category: 'meat', protein: 17, calories: 270, isHealthy: false },
  { name: 'Наденица по домашна рецепта', price: 5.11, unit: 'кг', category: 'meat', protein: 14, calories: 310, isHealthy: false },
  { name: 'Колбасички по сръбски', price: 7.15, unit: 'кг', category: 'meat', protein: 15, calories: 320, isHealthy: false },
  { name: 'Бейби суджук за скара', price: 8.43, unit: 'кг', category: 'meat', protein: 18, calories: 350, isHealthy: false },
  { name: 'Рагу варено-пушено', price: 2.04, unit: 'кг', category: 'meat', protein: 16, calories: 180, isHealthy: false },
  { name: 'САМИ-М Пилешки шницел', price: 5.00, unit: 'кг', category: 'meat', protein: 17, calories: 198, isHealthy: false },
  { name: 'Хотдог 100 г', price: 0.50, unit: 'бр.', category: 'meat', protein: 12, calories: 290, isHealthy: false },
  { name: 'COMPASS Пастет', price: 1.00, unit: 'бр.', category: 'meat', protein: 10, calories: 250, isHealthy: false },

  // ── FISH ──────────────────────────────────────────────────────────────────
  { name: 'Сьомга котлет Норвегия', price: 15.33, unit: 'кг', category: 'fish', protein: 20, calories: 208, isHealthy: true },
  { name: 'Сьомгова пъстърва филе', price: 11.49, unit: 'кг', category: 'fish', protein: 21, calories: 181, isHealthy: true },
  { name: 'Порции сьомга филе 4x125 г', price: 10.22, unit: 'бр.', category: 'fish', protein: 20, calories: 208, isHealthy: true },
  { name: 'Ципура прясна', price: 9.20, unit: 'кг', category: 'fish', protein: 20, calories: 96, isHealthy: true },
  { name: 'Скумрия изчистена', price: 4.59, unit: 'кг', category: 'fish', protein: 19, calories: 205, isHealthy: true },
  { name: 'Хек почистен размразен', price: 4.59, unit: 'кг', category: 'fish', protein: 17, calories: 86, isHealthy: true },
  { name: 'Рибно филе панирано', price: 5.11, unit: 'кг', category: 'fish', protein: 14, calories: 200, isHealthy: false },
  { name: 'Пангасиус филе размразено', price: 6.13, unit: 'кг', category: 'fish', protein: 15, calories: 83, isHealthy: true },
  { name: 'Сурови скариди размразени', price: 10.22, unit: 'кг', category: 'fish', protein: 19, calories: 85, isHealthy: true },
  { name: 'Черноморски миди BLACK SEA SHELLS 1 кг', price: 3.49, unit: 'бр.', category: 'fish', protein: 12, calories: 86, isHealthy: true },
  { name: 'OCEAN PICK Разбит хайвер 120 г', price: 0.50, unit: 'бр.', category: 'fish', protein: 25, calories: 245, isHealthy: true },

  // ── DAIRY ─────────────────────────────────────────────────────────────────
  { name: 'Кашкавал от краве мляко', price: 7.97, unit: 'кг', category: 'dairy', protein: 25, calories: 380, isHealthy: false },
  { name: 'Моцарела класик 125 г', price: 0.99, unit: 'бр.', category: 'dairy', protein: 18, calories: 240, isHealthy: true },
  { name: 'Минимоцарела 125 г', price: 1.00, unit: 'бр.', category: 'dairy', protein: 18, calories: 240, isHealthy: true },
  { name: 'LACRIMA Кашкавал 400 г', price: 5.00, unit: 'бр.', category: 'dairy', protein: 25, calories: 380, isHealthy: false },
  { name: 'ПЪРШЕВИЦА Сирене 600 г', price: 5.00, unit: 'бр.', category: 'dairy', protein: 14, calories: 240, isHealthy: true },
  { name: 'Прясно мляко UHT 1 л', price: 1.00, unit: 'бр.', category: 'dairy', protein: 3, calories: 63, isHealthy: true },
  { name: 'ВЕРЕЯ Прясно мляко 3% 2 л', price: 2.55, unit: 'бр.', category: 'dairy', protein: 3, calories: 60, isHealthy: true },
  { name: 'БАЛКАН Кисело мляко 3.6% 500 г', price: 0.65, unit: 'бр.', category: 'dairy', protein: 4, calories: 72, isHealthy: true },
  { name: 'ДОМЛЯН Кисело мляко 4.5% 500 г', price: 0.76, unit: 'бр.', category: 'dairy', protein: 4, calories: 80, isHealthy: true },
  { name: 'САЯНА Кисело мляко 2% 400 г', price: 0.50, unit: 'бр.', category: 'dairy', protein: 4, calories: 56, isHealthy: true },
  { name: 'БОР ЧВОР Сметана за готвене 1 л', price: 2.99, unit: 'бр.', category: 'dairy', protein: 2, calories: 200, isHealthy: false },
  { name: 'MONARCH Краве масло 82% 2x250 г', price: 4.29, unit: 'бр.', category: 'dairy', protein: 1, calories: 720, isHealthy: false },
  { name: 'MLEKOVITA Скир 500 г', price: 2.09, unit: 'бр.', category: 'dairy', protein: 10, calories: 66, isHealthy: true },
  { name: 'YOTIS Пудинг de la crème 70-84 г', price: 0.50, unit: 'бр.', category: 'dairy', protein: 3, calories: 120, isHealthy: false },
  { name: 'БОР ЧВОР Млечно-кисел десерт 200 г', price: 0.45, unit: 'бр.', category: 'dairy', protein: 3, calories: 110, isHealthy: false },
  { name: 'Закуска с топено сирене 110 г', price: 0.50, unit: 'бр.', category: 'dairy', protein: 8, calories: 180, isHealthy: false },

  // ── VEGETABLES ────────────────────────────────────────────────────────────
  { name: 'Жълт лук 5 кг', price: 1.65, unit: 'бр.', category: 'vegetables', protein: 1, calories: 40, isHealthy: true },
  { name: 'Тиквички', price: 1.53, unit: 'кг', category: 'vegetables', protein: 1, calories: 17, isHealthy: true },
  { name: 'Салата Айсберг', price: 0.99, unit: 'бр.', category: 'vegetables', protein: 1, calories: 14, isHealthy: true },
  { name: 'Гъби печурки 500 г', price: 1.78, unit: 'бр.', category: 'vegetables', protein: 3, calories: 22, isHealthy: true },
  { name: 'Моркови 500 г', price: 0.89, unit: 'бр.', category: 'vegetables', protein: 1, calories: 41, isHealthy: true },
  { name: 'Репички 250 г', price: 0.66, unit: 'бр.', category: 'vegetables', protein: 1, calories: 16, isHealthy: true },
  { name: 'Копър 1 връзка', price: 0.66, unit: 'бр.', category: 'vegetables', protein: 4, calories: 43, isHealthy: true },
  { name: 'Целина стъбла 400 г', price: 1.02, unit: 'бр.', category: 'vegetables', protein: 1, calories: 16, isHealthy: true },
  { name: 'Млечен чесън', price: 3.47, unit: 'кг', category: 'vegetables', protein: 6, calories: 149, isHealthy: true },
  { name: 'Български картофи четкани 5 кг', price: 1.75, unit: 'бр.', category: 'vegetables', protein: 2, calories: 77, isHealthy: true },
  { name: 'Червени картофи мити', price: 0.50, unit: 'кг', category: 'vegetables', protein: 2, calories: 77, isHealthy: true },
  { name: 'Ранно зеле', price: 0.75, unit: 'кг', category: 'vegetables', protein: 1, calories: 25, isHealthy: true },
  { name: 'БУЛКОНС Лютеница фино смляна 540 г', price: 1.00, unit: 'бр.', category: 'canned', protein: 2, calories: 80, isHealthy: true },

  // ── FRUIT ─────────────────────────────────────────────────────────────────
  { name: 'Портокали', price: 0.99, unit: 'кг', category: 'fruit', protein: 1, calories: 47, isHealthy: true },
  { name: 'Лимони 750 г', price: 1.78, unit: 'бр.', category: 'fruit', protein: 1, calories: 29, isHealthy: true },
  { name: 'Боровинки 200 г', price: 2.69, unit: 'бр.', category: 'fruit', protein: 1, calories: 57, isHealthy: true },
  { name: 'Круши Конференс', price: 1.78, unit: 'кг', category: 'fruit', protein: 0, calories: 57, isHealthy: true },
  { name: 'Авокадо', price: 0.59, unit: 'бр.', category: 'fruit', protein: 2, calories: 160, isHealthy: true },
  { name: 'Биобанани', price: 1.69, unit: 'кг', category: 'fruit', protein: 1, calories: 89, isHealthy: true },
  { name: 'Червено грозде 500 г', price: 2.04, unit: 'бр.', category: 'fruit', protein: 1, calories: 69, isHealthy: true },
  { name: 'Диня', price: 1.88, unit: 'кг', category: 'fruit', protein: 1, calories: 30, isHealthy: true },
  { name: 'Ягоди 250 г', price: 0.99, unit: 'бр.', category: 'fruit', protein: 1, calories: 32, isHealthy: true },
  { name: 'Червени ябълки', price: 0.71, unit: 'кг', category: 'fruit', protein: 0, calories: 52, isHealthy: true },

  // ── BAKERY ────────────────────────────────────────────────────────────────
  { name: 'Вита баница 460 г', price: 2.00, unit: 'бр.', category: 'bakery', protein: 7, calories: 310, isHealthy: false },
  { name: 'Геврек със сирене и сусам 100 г', price: 0.50, unit: 'бр.', category: 'bakery', protein: 9, calories: 290, isHealthy: false },
  { name: 'ТИМС Кифлички 250 г', price: 1.00, unit: 'бр.', category: 'bakery', protein: 8, calories: 270, isHealthy: false },
  { name: 'MC GOLD Хлебчета 260-300 г', price: 1.00, unit: 'бр.', category: 'bakery', protein: 9, calories: 265, isHealthy: false },
  { name: 'Бял хляб нарязан 650 г', price: 0.66, unit: 'бр.', category: 'bakery', protein: 8, calories: 265, isHealthy: false },
  { name: 'ВИТА СИЛУЕТ Хляб 400 г', price: 1.22, unit: 'бр.', category: 'bakery', protein: 9, calories: 220, isHealthy: true },
  { name: 'Ръжен хляб 600 г', price: 0.81, unit: 'бр.', category: 'bakery', protein: 9, calories: 259, isHealthy: true },
  { name: 'Кроасан с шунка и кашкавал 95 г', price: 0.61, unit: 'бр.', category: 'bakery', protein: 10, calories: 310, isHealthy: false },
  { name: 'Донът с ягодов пълнеж 70 г', price: 0.39, unit: 'бр.', category: 'bakery', protein: 5, calories: 340, isHealthy: false },
  { name: 'Багета пълнозърнеста 110 г', price: 0.17, unit: 'бр.', category: 'bakery', protein: 8, calories: 240, isHealthy: true },
  { name: 'Пърленка по сръбска рецепта 160 г', price: 0.35, unit: 'бр.', category: 'bakery', protein: 9, calories: 260, isHealthy: false },
  { name: 'Бял земел 60 г', price: 0.05, unit: 'бр.', category: 'bakery', protein: 8, calories: 268, isHealthy: false },
  { name: 'Кроасан с 24% масло 55 г', price: 0.28, unit: 'бр.', category: 'bakery', protein: 7, calories: 400, isHealthy: false },

  // ── GRAINS & PASTA ────────────────────────────────────────────────────────
  { name: 'ТОПАЗ МЕЛ Пшенично брашно тип 500 1 кг', price: 0.76, unit: 'бр.', category: 'grains', protein: 10, calories: 340, isHealthy: false },
  { name: 'ИНКОМ Ориз бисерен 1 кг', price: 1.53, unit: 'бр.', category: 'grains', protein: 7, calories: 360, isHealthy: false },
  { name: 'INDOMIE Инстантни нудли 420-450 г', price: 1.53, unit: 'бр.', category: 'grains', protein: 8, calories: 430, isHealthy: false },
  { name: 'NESTLE Зърнена закуска 550-625 г', price: 4.08, unit: 'бр.', category: 'grains', protein: 8, calories: 380, isHealthy: false },
  { name: 'Овесени ядки 500 г', price: 0.50, unit: 'бр.', category: 'grains', protein: 13, calories: 389, isHealthy: true },
  { name: 'BARILLA Макаронени изделия 500 г', price: 1.17, unit: 'бр.', category: 'grains', protein: 13, calories: 352, isHealthy: false },
  { name: 'КРЪСТЕВ Макаронени изделия 2x400 г', price: 0.84, unit: 'бр.', category: 'grains', protein: 13, calories: 352, isHealthy: false },

  // ── LEGUMES ───────────────────────────────────────────────────────────────
  { name: 'NATURA Червена леща 500 г', price: 1.00, unit: 'бр.', category: 'legumes', protein: 9, calories: 116, isHealthy: true },
  { name: 'KRINA Леща екстра 1 кг', price: 2.00, unit: 'бр.', category: 'legumes', protein: 9, calories: 116, isHealthy: true },
  { name: 'CAMPESE Бял боб 540 г', price: 1.27, unit: 'бр.', category: 'legumes', protein: 7, calories: 110, isHealthy: true },
  { name: 'CAMPESE Червен боб 540 г', price: 1.27, unit: 'бр.', category: 'legumes', protein: 9, calories: 127, isHealthy: true },
  { name: 'CAMPESE Нахут 540 г', price: 1.27, unit: 'бр.', category: 'legumes', protein: 9, calories: 164, isHealthy: true },
  { name: 'CHEF CARLO Грах 400 г', price: 0.51, unit: 'бр.', category: 'legumes', protein: 5, calories: 84, isHealthy: true },

  // ── SNACKS & SWEETS ───────────────────────────────────────────────────────
  { name: 'FERRERO ROCHER 200 г', price: 5.00, unit: 'бр.', category: 'snacks', protein: 8, calories: 573, isHealthy: false },
  { name: 'MILKA Бисквити 150-260 г', price: 2.00, unit: 'бр.', category: 'snacks', protein: 6, calories: 480, isHealthy: false },
  { name: 'MILKA Кексчета 140-175 г', price: 2.00, unit: 'бр.', category: 'snacks', protein: 5, calories: 430, isHealthy: false },
  { name: 'MILKA MMMAX Шоколад 250-300 г', price: 3.57, unit: 'бр.', category: 'snacks', protein: 6, calories: 535, isHealthy: false },
  { name: 'KIT KAT Шоколад 99 г', price: 1.53, unit: 'бр.', category: 'snacks', protein: 6, calories: 515, isHealthy: false },
  { name: 'KIT KAT CHUNKY 40-42 г', price: 0.50, unit: 'бр.', category: 'snacks', protein: 6, calories: 515, isHealthy: false },
  { name: 'MERCI Шоколадови бонбони 210-250 г', price: 4.49, unit: 'бр.', category: 'snacks', protein: 7, calories: 545, isHealthy: false },
  { name: 'KATY Шоколадови бонбони асорти 400 г', price: 3.21, unit: 'бр.', category: 'snacks', protein: 5, calories: 520, isHealthy: false },
  { name: 'СЕЗОНИ Шоколадови бонбони 140 г', price: 2.00, unit: 'бр.', category: 'snacks', protein: 5, calories: 490, isHealthy: false },
  { name: 'ПРЕСТИЖ Бисквити Роден край 165-170 г', price: 0.99, unit: 'бр.', category: 'snacks', protein: 6, calories: 460, isHealthy: false },
  { name: 'SWEET PLUS Бисквити 140-165 г', price: 1.00, unit: 'бр.', category: 'snacks', protein: 6, calories: 470, isHealthy: false },
  { name: 'VARNA Минивафли 260 г', price: 1.53, unit: 'бр.', category: 'snacks', protein: 5, calories: 490, isHealthy: false },
  { name: 'МОРЕНИ Тунквана вафла 34-36 г', price: 0.28, unit: 'бр.', category: 'snacks', protein: 4, calories: 480, isHealthy: false },
  { name: 'PRINGLES Чипс 160-165 г', price: 2.04, unit: 'бр.', category: 'snacks', protein: 6, calories: 530, isHealthy: false },
  { name: 'LAYS Картофен чипс 2x240 г', price: 1.82, unit: 'бр.', category: 'snacks', protein: 6, calories: 536, isHealthy: false },
  { name: 'STAR Снакс 80-100 г', price: 0.61, unit: 'бр.', category: 'snacks', protein: 5, calories: 490, isHealthy: false },
  { name: 'ROIS Сурови ядки 150 г', price: 2.00, unit: 'бр.', category: 'snacks', protein: 15, calories: 580, isHealthy: true },
  { name: 'NUCREMA Какаов крем 2x650 г', price: 5.11, unit: 'бр.', category: 'snacks', protein: 5, calories: 530, isHealthy: false },
  { name: 'ELIT Кейк Идеал 72 г', price: 0.50, unit: 'бр.', category: 'snacks', protein: 4, calories: 380, isHealthy: false },
  { name: 'ЛУКЧЕТА Бонбони 75 г', price: 0.50, unit: 'бр.', category: 'snacks', protein: 0, calories: 380, isHealthy: false },

  // ── FROZEN ────────────────────────────────────────────────────────────────
  { name: 'Пица Маргарита 3x300 г', price: 3.32, unit: 'бр.', category: 'frozen', protein: 9, calories: 250, isHealthy: false },
  { name: 'FAMILIA COLLECTION Сладолед 900 мл', price: 3.19, unit: 'бр.', category: 'frozen', protein: 3, calories: 200, isHealthy: false },
  { name: 'FAMILIA HIT Сладолед Chocomania 60-67 г', price: 0.79, unit: 'бр.', category: 'frozen', protein: 3, calories: 210, isHealthy: false },
  { name: 'MILKA/OREO/TOBLERONE Сладолед 64-94 г', price: 2.00, unit: 'бр.', category: 'frozen', protein: 3, calories: 200, isHealthy: false },
  { name: 'NUII Сладолед 6 бр.', price: 5.00, unit: 'бр.', category: 'frozen', protein: 3, calories: 240, isHealthy: false },
  { name: 'DELICHE Сладолед 900 мл / 2000 мл', price: 2.80, unit: 'бр.', category: 'frozen', protein: 3, calories: 190, isHealthy: false },
  { name: 'САМИ-М Пръчици с кашкавал 400 г', price: 1.72, unit: 'бр.', category: 'frozen', protein: 9, calories: 250, isHealthy: false },
  { name: 'PENELOPE Цяла патица', price: 3.57, unit: 'кг', category: 'frozen', protein: 18, calories: 337, isHealthy: false },
  { name: 'Пилешки фенер', price: 0.81, unit: 'кг', category: 'frozen', protein: 14, calories: 200, isHealthy: false },
  { name: 'САМИ-М Пилешки хапки 1 кг', price: 2.79, unit: 'бр.', category: 'frozen', protein: 15, calories: 220, isHealthy: false },

  // ── DRINKS ────────────────────────────────────────────────────────────────
  { name: 'COCA-COLA/FANTA/SPRITE 1.5 л', price: 1.17, unit: 'бр.', category: 'drinks', protein: 0, calories: 42, isHealthy: false },
  { name: 'MONSTER Енергийна напитка 500 мл', price: 1.00, unit: 'бр.', category: 'drinks', protein: 0, calories: 46, isHealthy: false },
  { name: 'CRAZY WOLF Енергийна напитка 0.25 л', price: 0.29, unit: 'бр.', category: 'drinks', protein: 0, calories: 46, isHealthy: false },
  { name: 'ХИСАР Натурална минерална вода 10 л', price: 1.53, unit: 'бр.', category: 'drinks', protein: 0, calories: 0, isHealthy: true },
  { name: 'BEBELAN Вода за кърмачета 1.5 л', price: 0.50, unit: 'бр.', category: 'drinks', protein: 0, calories: 0, isHealthy: true },
  { name: 'GRENO Сок 100% 1 л', price: 2.00, unit: 'бр.', category: 'drinks', protein: 1, calories: 45, isHealthy: true },
  { name: 'DELLOS Напитка Aloe vera 1.5 л', price: 2.00, unit: 'бр.', category: 'drinks', protein: 0, calories: 26, isHealthy: false },
  { name: 'PRISUN Плодова напитка 2 л', price: 1.12, unit: 'бр.', category: 'drinks', protein: 0, calories: 40, isHealthy: false },
  { name: 'ВВВ Нектар или Плодова напитка 1 л', price: 1.49, unit: 'бр.', category: 'drinks', protein: 0, calories: 50, isHealthy: false },
  { name: 'SAN TERRA Газирана напитка 2.5 л', price: 0.45, unit: 'бр.', category: 'drinks', protein: 0, calories: 40, isHealthy: false },
  { name: 'БАНКЯ Минерална вода 6x1.5 л', price: 2.55, unit: 'бр.', category: 'drinks', protein: 0, calories: 0, isHealthy: true },
  { name: 'DEVIN Вода 8x0.5 л', price: 2.49, unit: 'бр.', category: 'drinks', protein: 0, calories: 0, isHealthy: true },
  { name: 'FUZE TEA Студен чай 6x1.5 л', price: 7.12, unit: 'бр.', category: 'drinks', protein: 0, calories: 26, isHealthy: false },

  // ── ALCOHOL & BEER ────────────────────────────────────────────────────────
  { name: 'ПИРИНСКО Бира 2 л PET', price: 1.09, unit: 'бр.', category: 'alcohol', protein: 0, calories: 43, isHealthy: false },
  { name: 'ПИРИНСКО Младо пиво 0.5 л', price: 0.55, unit: 'бр.', category: 'alcohol', protein: 0, calories: 43, isHealthy: false },
  { name: 'ЗАГОРКА Бира 0.5 л кен', price: 0.55, unit: 'бр.', category: 'alcohol', protein: 0, calories: 43, isHealthy: false },
  { name: 'ШУМЕНСКО Бира 0.33 л', price: 0.40, unit: 'бр.', category: 'alcohol', protein: 0, calories: 43, isHealthy: false },
  { name: 'ASTIKA Бира 0.5 л кен', price: 0.49, unit: 'бр.', category: 'alcohol', protein: 0, calories: 43, isHealthy: false },
  { name: 'АРИАНА Бира 9x0.5 л кен', price: 4.08, unit: 'бр.', category: 'alcohol', protein: 0, calories: 43, isHealthy: false },
  { name: 'БУРГАСКО Бира 8x0.5 л кен', price: 4.10, unit: 'бр.', category: 'alcohol', protein: 0, calories: 43, isHealthy: false },
  { name: 'HEINEKEN Бира 9x0.5 л кен', price: 6.13, unit: 'бр.', category: 'alcohol', protein: 0, calories: 42, isHealthy: false },
  { name: 'STELLA ARTOIS Бира 8x0.5 л кен', price: 5.62, unit: 'бр.', category: 'alcohol', protein: 0, calories: 43, isHealthy: false },
  { name: 'PAULANER Бира 4x0.5 л кен', price: 4.59, unit: 'бр.', category: 'alcohol', protein: 0, calories: 47, isHealthy: false },
  { name: 'TUBORG Бира 6x0.5 л кен', price: 3.57, unit: 'бр.', category: 'alcohol', protein: 0, calories: 43, isHealthy: false },
  { name: 'SOMERSBY Сайдер 0.33 л', price: 0.81, unit: 'бр.', category: 'alcohol', protein: 0, calories: 39, isHealthy: false },
  { name: 'ZLATEN ROZHEN Вино 0.75 л', price: 5.00, unit: 'бр.', category: 'alcohol', protein: 0, calories: 85, isHealthy: false },
  { name: 'MEZZEK Вино 0.75 л', price: 5.11, unit: 'бр.', category: 'alcohol', protein: 0, calories: 85, isHealthy: false },
  { name: 'ГРОЗДЕН Спиртна напитка 0.7 л', price: 5.00, unit: 'бр.', category: 'alcohol', protein: 0, calories: 222, isHealthy: false },
  { name: 'JACK DANIELS 0.7 л', price: 18.99, unit: 'бр.', category: 'alcohol', protein: 0, calories: 222, isHealthy: false },
  { name: 'TULLAMORE DEW Ирландско уиски 1 л', price: 15.84, unit: 'бр.', category: 'alcohol', protein: 0, calories: 222, isHealthy: false },
  { name: 'BALLANTINE\'S FINEST Шотландско уиски 0.7 л', price: 12.26, unit: 'бр.', category: 'alcohol', protein: 0, calories: 222, isHealthy: false },
  { name: 'SMIRNOFF NO.21 Водка 1 л', price: 10.73, unit: 'бр.', category: 'alcohol', protein: 0, calories: 231, isHealthy: false },
  { name: 'JÄGERMEISTER Ликьор 0.7 л', price: 11.24, unit: 'бр.', category: 'alcohol', protein: 0, calories: 305, isHealthy: false },
  { name: 'ПЕЩЕРА Мастика 0.7 л', price: 5.31, unit: 'бр.', category: 'alcohol', protein: 0, calories: 230, isHealthy: false },
  { name: 'APEROL & CINZANO промопакет 0.7+0.75 л', price: 15.33, unit: 'бр.', category: 'alcohol', protein: 0, calories: 150, isHealthy: false },
  { name: 'MARTINI Пенливо вино 0.75 л', price: 10.22, unit: 'бр.', category: 'alcohol', protein: 0, calories: 95, isHealthy: false },

  // ── COFFEE ────────────────────────────────────────────────────────────────
  { name: 'NESCAFE Dolce Gusto 3x16 бр.', price: 13.29, unit: 'бр.', category: 'coffee', protein: 0, calories: 5, isHealthy: false },
  { name: 'NESCAFE Разтворимо кафе 3в1 310 г', price: 2.96, unit: 'бр.', category: 'coffee', protein: 1, calories: 370, isHealthy: false },
  { name: 'JACOBS Разтворимо кафе Monarch 200 г', price: 8.17, unit: 'бр.', category: 'coffee', protein: 12, calories: 290, isHealthy: false },
  { name: 'LAVAZZA Мляно кафе Crema e Gusto 250 г', price: 5.00, unit: 'бр.', category: 'coffee', protein: 12, calories: 290, isHealthy: false },
  { name: 'LAVAZZA Кафе на зърна Crema e Gusto Forte 1 кг', price: 17.69, unit: 'бр.', category: 'coffee', protein: 12, calories: 290, isHealthy: false },
  { name: 'GALA Мляно кафе Ala Carte 500 г', price: 5.62, unit: 'бр.', category: 'coffee', protein: 12, calories: 290, isHealthy: false },
  { name: 'DAVIDOFF Кафе на зърна 500 г', price: 14.80, unit: 'бр.', category: 'coffee', protein: 12, calories: 290, isHealthy: false },
  { name: 'EDUSCHO Кафе на зърна 1 кг', price: 15.33, unit: 'бр.', category: 'coffee', protein: 12, calories: 290, isHealthy: false },
  { name: 'NOVA BRASILIA Мляно кафе 200 г', price: 2.49, unit: 'бр.', category: 'coffee', protein: 12, calories: 290, isHealthy: false },

  // ── OILS & CONDIMENTS ─────────────────────────────────────────────────────
  { name: 'КЛАС Олио слънчогледово 1 л', price: 1.22, unit: 'бр.', category: 'oils', protein: 0, calories: 884, isHealthy: false },
  { name: 'COSTA D\'ORO Маслиново масло Extra Virgin 750 мл', price: 5.99, unit: 'бр.', category: 'oils', protein: 0, calories: 884, isHealthy: true },
  { name: 'COPPINI Маслиново масло Extra Virgin 1 л', price: 8.67, unit: 'бр.', category: 'oils', protein: 0, calories: 884, isHealthy: true },
  { name: 'SUNFLORO Шарлан горещо пресован 1 л', price: 2.30, unit: 'бр.', category: 'oils', protein: 0, calories: 884, isHealthy: false },
  { name: 'HEINZ Кетчуп 1 кг', price: 3.06, unit: 'бр.', category: 'canned', protein: 1, calories: 112, isHealthy: false },
  { name: 'MAGGI Фикс или Супа 27-60 г', price: 0.76, unit: 'бр.', category: 'canned', protein: 5, calories: 330, isHealthy: false },
  { name: 'BARILLA Сос Песто 190-200 г', price: 2.49, unit: 'бр.', category: 'canned', protein: 6, calories: 430, isHealthy: false },
  { name: 'MUTTI Домати 400 г', price: 1.53, unit: 'бр.', category: 'canned', protein: 2, calories: 35, isHealthy: true },
  { name: 'POMI Доматено пюре 700 г', price: 1.59, unit: 'бр.', category: 'canned', protein: 2, calories: 35, isHealthy: true },
  { name: 'SILVA Лазаня 1.1 кг', price: 4.09, unit: 'бр.', category: 'canned', protein: 9, calories: 290, isHealthy: false },
];
